app/course/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, FileField
from flask_wtf.file import FileRequired
from wtforms import TextAreaField, DateTimeField
from flask_pagedown.fields import PageDownField
from wtforms.validators import DataRequired, Length, Email

class CreateCourseForm(FlaskForm):
    course_name = StringField('课程名', validators=[DataRequired()])
    student_list = FileField('学生名单')
    submit = SubmitField('提交')

app/course/__init__.py
from flask import Blueprint

course = Blueprint('course', __name__)

from . import views

app/course/views.py
import os
import random
import csv

from . import course
from flask import Flask, render_template, redirect, url_for, flash, session
from flask import request, send_from_directory, send_file
from flask_login import UserMixin, login_required
from flask_login import current_user, logout_user, login_user
from werkzeug.utils import secure_filename

from .forms import *
from ..models import *
from .. import db
from ..util import *

@course.route('/course-list')
@login_required
def course_list():
    courses = []
    for role in current_user.courses:
        for user in role.course.users:
            if user.role == 'teacher':
                teacher = user.user
        courses.append((role.course, teacher))

    return render_template('courses/course_list.html', courses=courses)

@course.route('/create-course', methods=['GET', 'POST'])
@login_required
def course_create():
    form = CreateCourseForm()
    if form.validate_on_submit():
        course = Course(name=form.course_name.data)
        role = Role(role='teacher')
        role.user = current_user
        role.course = course

        file = form.student_list.data
        if file != '':
            rand_filename = str(random.randint(0, 100000)) \
                            + secure_filename(file.filename)
            path = 'app/static/tmp'
            os.makedirs(path, exist_ok=True)
            file.save(os.path.join(path, rand_filename))
            add_member(os.path.join(path, rand_filename), course)
            os.remove(os.path.join(path, rand_filename))
            
        db.session.add(course)
        db.session.add(role)
        db.session.commit()
        flash('课程创建成功')
        return redirect(url_for('.course_list'))
    return render_template('courses/course_create.html', form=form) 

@course.route('/course/<id>')
def course_page(id):
    course = Course.query.get_or_404(id)
    return render_template('courses/course.html', course=course, teacher=getTeacher(course))

def createUser(id, name):
    u = User(id=id, name=name, password=str(id))
    db.session.add(u)
    return u

def add_member(filename, course):
    with open(filename, newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            user = User.query.get(row['id'])
            if not user:
                user = createUser(row['id'], row['name'])
            role = Role(role='student')
            role.user = user
            role.course = course
            db.session.add(role)
            

app/templates/401.html
{% extends "error.html" %}

{% block title %}Course - Unauthorized{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Unauthorized</h1>
</div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Course{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">
<!-- <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon"> -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" type="text/css">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Course</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {% if current_user.is_authenticated %}
                <li>
                    <a href="{{ url_for('profile.profile_user', id=current_user.id) }}">
                        个人简介
                    </a>
                </li>
                <li>
                    <a href="{{ url_for('course.course_create') }}">
                        创建课程
                    </a>
                </li>
                <li>
                    <a href="{{ url_for('course.course_list') }}">
                        课程列表
                    </a>
                </li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li>
                    <a href="{{ url_for('main.logout') }}">
                        登出
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times</button>
        {{ message }}
    </div>
    {% endfor %}
</div>
<div class="container">
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/course.html
{% extends "courses/course_base.html" %}

{% block head %}
   <meta charset="utf-8"> 
   <title>course</title>
   <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">  
   <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
   <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% endblock %}

{% block page_content %}
<div class="container">
<section class="row" style="min-height: 400px; background-color: white;">
	<div class="col-sm-12 col-md-12 col-lg-6 col-xl-6" style="padding: 0px;">
		<div style="background-color: #993333; width: 100%; height: 100%; display: flex; align-items: center; justify-content: center; min-height: 400px; padding: 3rem">
			<h1 style="color: white; font-size: 4rem; ">{{ course.name }}</h1>
		</div>
	</div>
	<div class="col-sm-12 col-md-12 col-lg-6 col-xl-6" style="padding: 0px">
		<div style="width: 100%; height: 100%; display: flex;align-items: center; justify-content: center; min-height: 400px; padding: 3rem">
		<h1 style="color:#666666; font-size: 4rem;"> 学而时习之，不亦说乎</h1>
		</div>
	</div>
</section>
<section class="row" style="flex-direction: column-reverse; min-height: 400px; background-color: white;">
	<div class="col-sm-12 col-md-12 col-lg-6 col-xl-6" style="padding: 0px">
		<div style="width: 100%; height: 100%; display: flex;align-items: center; justify-content: center; min-height: 400px; padding: 3rem">
		<h1 style="color:#666666; font-size: 4rem;">书犹药也，可以医愚</h1>
		</div>
	</div>
	<div class="col-sm-12 col-md-12 col-lg-6 col-xl-6" style="padding: 0px;">
		<div style="background-color: #993333; padding: 3rem; width: 100%; height: 100%; display: flex; align-items: center; justify-content: center; min-height: 400px;">
			<h2 style="color: white; font-size: 4rem; ">教师: {{ teacher.name }} </h2>
		</div>
	</div>
</section>
</div>
{% endblock %}

app/templates/course_base.html
{% extends "bootstrap/base.html" %}

{% block title %}Course{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">
<!-- <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon"> -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" type="text/css">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
    body {
        position: relative; 
    }
    .zoomIn {
        -webkit-animation-name: zoomIn;
        animation-name: zoomIn;
    }
    .animated {
        -webkit-animation-duration: 1s;
        animation-duration: 1s;
        -webkit-animation-fill-mode: both;
        animation-fill-mode: both;
    }
    @-webkit-keyframes zoomIn {
        0% {
            opacity: 0;
            -webkit-transform: scale(.3);
            transform: scale(.3);
        }

        50% {
            opacity: 1;
        }
    }
    @keyframes zoomIn {
        0% {
            opacity: 0;
            -webkit-transform: scale(.3);
            -ms-transform: scale(.3);
            transform: scale(.3);
        }

        50% {
            opacity: 1;
        }
    }

    @keyframes longerOne {
        100% {width: 500px;}
    }

    @-webkit-keyframes longerOne {
        100% {width: 500px;}
    }

    @keyframes longerTwo {
        100% {width: 675px;}
    }

    @-webkit-keyframes longerTwo {
        100% {width: 675px;}
    }

    @keyframes longerThree {
        100% {width: 1000px;}
    }

    @-webkit-keyframes longerThree {
        100% {width: 1000px;}
    }

</style>
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">	
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">	
                <span class="sr-only">Toggle navigation</span>	
                <span class="icon-bar"></span>	
                <span class="icon-bar"></span>	
                <span class="icon-bar"></span>	
            </button>	
            <a class="navbar-brand" href="/">Course</a>	
        </div>	
        <div class="navbar-collapse collapse">	
            <ul class="nav navbar-nav">	
				{% if current_user.is_authenticated %}	
                <li>	
                    <a href="{{ url_for('profile.profile_user', id=current_user.id) }}">
                        个人简介	
                    </a>	
                </li>	
                <li>	
                    <a href="{{ url_for('course.course_create') }}">
                        创建课程	
                    </a>	
                </li>	
                <li>	
                    <a href="{{ url_for('course.course_list') }}">	
                        课程列表	
                    </a>	
                </li>	
                <li>	
                    <a href="{{ url_for('homework.homework_list', id=course.id) }}">	
                        课程作业	
                    </a>	
                </li>
                {% if current_user.id in course.get_teacher() %}	
                <li>	
                    <a href="{{ url_for('homework.homework_publish', id=course.id) }}">	
                        发布作业	
                    </a>	
                </li>	
                {% endif %}
                {% endif %}		
            </ul>	
            <ul class="nav navbar-nav navbar-right">
            	{% if current_user.is_authenticated %}		
                <li>	
                    <a href="{{ url_for('main.logout') }}">	
                        登出	
                    </a>	
                </li>	
                {% endif %}	
            </ul>	
        </div>	
    </div>	
</div>	
{% endblock %}

{% block content %}

<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times</button>
        {{ message }}
    </div>
    {% endfor %}
</div>
<div class="container">
    {% block page_content %}
    <section style="min-height: 400px; background-color: white">
        <div class="animated zoomIn animated" style="visibility: visible; padding-top: 80px; animation-delay: 0.5s; animation-name: zoomIn;">
            <h1 style="color: black; font-size: 4rem;"><span></span>Course Master</h1>
        </div>
    </section>

    <div style="width: 100px; height: 25px; background-color: #1E88E5; margin-bottom: 20px; animation-name: longerOne 1s; -webkit-animation: longerOne 2s; animation-fill-mode: both;"></div>
    <div style="width: 200px; height: 25px; background-color: #993333; margin-bottom: 20px; animation: longerTwo 2s; -webkit-animation: longerTwo 2s; animation-fill-mode: both;"></div>
    <div style="width: 500px; height: 25px; background-color: #00bcd4; animation: longerThree 2s; -webkit-animation: longerThree 2s; animation-fill-mode: both;"></div>


    {% endblock %}
</div>

{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/course_create.html
{% extends "courses/course_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="container">
	<section style="min-height: 200px; background-color: white">
        <div class="animated zoomIn animated" style="visibility: visible; padding-top: 80px; animation-delay: 0.5s; animation-name: zoomIn;">
            <h1 style="color: black; font-size: 4rem;"><span></span>Course Master</h1>
        </div>
    </section>

    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
</div>
{% endblock %}

app/templates/course_list.html
{% extends "courses/course_base.html" %}

{% block head %}
  <meta charset="utf-8">
    <title>course_list</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        body {
            position: relative; 
        }
    </style>
{% endblock %}


{% block content %}

{% set bgcolor = 1 %}

{% for course, teacher in courses %}
<div style="padding-top: 50px; height: 200px; color: #fff; background-color: {% if bgcolor is equalto 1 %}
    #1E88E5
    {% elif bgcolor is equalto 2 %}
    #673ab7
    {% elif bgcolor is equalto 3 %}
    #ff9800
    {% elif bgcolor is equalto 4 %}
    #00bcd4
    {% else %}
    #009688
    {% endif %};" class = "container-fluid">
    <a href="{{ url_for('course.course_page', id=course.id) }}" >
        <h1 style="color: white;">{{ course.name }}</h1>
        <p style="color: white;">教师: {{ teacher.name }}</p>
    </a>
</div>
{% set bgcolor = bgcolor + 1 %}
{% if bgcolor is equalto 6 %}
    {% set bgcolor = 1 %}
{% endif %}
{% endfor %}

{% endblock %}

app/templates/create_course.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
</div>
{% endblock %}

app/templates/error.html
{% extends "base.html" %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Course</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/error_401.html
{% extends "error_base.html" %}

{% block title %}Course - Unauthorized{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Unauthorized</h1>
</div>
{% endblock %}

app/templates/error_404.html
{% extends "error_base.html" %}

{% block title %}Course - Page Not Found{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Not Found</h1>
</div>
{% endblock %}

app/templates/error_500.html
{% extends "error_base.html" %}

{% block title %}Course - Internal Server Error{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Internal Server Error</h1>
</div>
{% endblock %}

app/templates/homework_list.html
{% extends 'course_base.html' %}

{% block page_content %}
{% for hw in course.homework %}
<div class="col-md-4">
    <a href="{{ url_for('course.homework', id=course.id, hw_id=hw.id) }}">
        <h2>{{ hw.title }}</h2>
    </a>
    <p>begin: {{ hw.begin_time }}</p>
    <p>end: {{ hw.end_time }}</p>
</div>
{% endfor %}
{% endblock %}

app/templates/homework_publish.html
{% extends 'course_base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block page_content %}
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/publish_homework.html
{% extends 'course_base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block page_content %}
{{ wtf.quick_form(form) }}
{% endblock %}